{{- if .Values.snuba.subscriptionConsumerEapSpans.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-snuba-subscription-consumer-eap-spans
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "18"
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: snuba-subscription-consumer-eap-spans
  replicas: {{ .Values.snuba.subscriptionConsumerEapSpans.replicas }}
  template:
    metadata:
      annotations:
        checksum/snubaSettingsPy: {{ .Values.config.snubaSettingsPy | sha256sum }}
        checksum/config.yaml: {{ include "sentry.snuba.config" . | sha256sum }}
        {{- if .Values.snuba.subscriptionConsumerEapSpans.annotations }}
{{ toYaml .Values.snuba.subscriptionConsumerEapSpans.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: snuba-subscription-consumer-eap-spans
        {{- if .Values.snuba.subscriptionConsumerEapSpans.podLabels }}
{{ toYaml .Values.snuba.subscriptionConsumerEapSpans.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.snuba.subscriptionConsumerEapSpans.affinity }}
{{ toYaml .Values.snuba.subscriptionConsumerEapSpans.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.subscriptionConsumerEapSpans.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.snuba.subscriptionConsumerEapSpans.nodeSelector | indent 8 }}
      {{- else if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.subscriptionConsumerEapSpans.tolerations }}
      tolerations:
{{ toYaml .Values.snuba.subscriptionConsumerEapSpans.tolerations | indent 8 }}
      {{- else if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.subscriptionConsumerEapSpans.topologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml .Values.snuba.subscriptionConsumerEapSpans.topologySpreadConstraints | indent 8 }}
      {{- end }}
      {{- if .Values.images.snuba.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.snuba.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.subscriptionConsumerEapSpans.securityContext }}
      securityContext:
{{ toYaml .Values.snuba.subscriptionConsumerEapSpans.securityContext | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-snuba
        image: "{{ template "snuba.image" . }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.snuba.pullPolicy }}
        command:
          - "snuba"
          - "subscriptions-scheduler-executor"
          {{- if .Values.snuba.subscriptionConsumerEapSpans.autoOffsetReset }}
          - "--auto-offset-reset"
          - "{{ .Values.snuba.subscriptionConsumerEapSpans.autoOffsetReset }}"
          {{- end }}
          - "--dataset=events_analytics_platform"
          - "--entity=eap_spans"
          {{- if .Values.snuba.subscriptionConsumerEapSpans.noStrictOffsetReset }}
          - "--no-strict-offset-reset"
          {{- end }}
          - "--consumer-group=snuba-eap-spans-subscriptions-consumers"
          - "--followed-consumer-group=eap_spans_group"
          - "--schedule-ttl=60"
          - "--stale-threshold-seconds=900"
          {{- if .Values.snuba.subscriptionConsumerEapSpans.livenessProbe.enabled }}
          - "--health-check-file"
          - "/tmp/health.txt"
          {{- end }}
        {{- if .Values.snuba.subscriptionConsumerEapSpans.livenessProbe.enabled }}
        livenessProbe:
          exec:
            command:
              - rm
              - /tmp/health.txt
          initialDelaySeconds: {{ .Values.snuba.subscriptionConsumerEapSpans.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.snuba.subscriptionConsumerEapSpans.livenessProbe.periodSeconds }}
        {{- end }}
        ports:
        - containerPort: {{ template "snuba.port" }}
        env:
{{ include "sentry.snuba.env" . | indent 8 }}
{{- if .Values.snuba.subscriptionConsumerEapSpans.env }}
{{ toYaml .Values.snuba.subscriptionConsumerEapSpans.env | indent 8 }}
{{- end }}
        envFrom:
        - secretRef:
            name: {{ template "sentry.fullname" . }}-snuba-env
        volumeMounts:
        - mountPath: /etc/snuba
          name: config
          readOnly: true
{{- if .Values.snuba.subscriptionConsumerEapSpans.volumeMounts }}
{{ toYaml .Values.snuba.subscriptionConsumerEapSpans.volumeMounts | indent 8 }}
{{- end }}
        resources:
{{ toYaml .Values.snuba.subscriptionConsumerEapSpans.resources | indent 12 }}
{{- if .Values.snuba.subscriptionConsumerEapSpans.containerSecurityContext }}
        securityContext:
{{ toYaml .Values.snuba.subscriptionConsumerEapSpans.containerSecurityContext | indent 12 }}
{{- end }}
{{- if .Values.snuba.subscriptionConsumerEapSpans.sidecars }}
{{ toYaml .Values.snuba.subscriptionConsumerEapSpans.sidecars | indent 6 }}
{{- end }}
{{- if .Values.global.sidecars }}
{{ toYaml .Values.global.sidecars | indent 6 }}
{{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}-snuba
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "sentry.fullname" . }}-snuba
{{- if .Values.snuba.subscriptionConsumerEapSpans.volumes }}
{{ toYaml .Values.snuba.subscriptionConsumerEapSpans.volumes | indent 6 }}
{{- end }}
{{- if .Values.global.volumes }}
{{ toYaml .Values.global.volumes | indent 6 }}
{{- end }}
{{- end }}
