{{- if .Values.pgbouncer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sentry.fullname" . }}-pgbouncer
spec:
  selector:
    app: {{ template "sentry.fullname" . }}-pgbouncer
  ports:
  - name: pgbouncer
    port: 5432
    targetPort: 5432
{{- end }}
