{{- if .Values.pgbouncer.enabled }}
{{- if .Values.pgbouncer.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "sentry.fullname" . }}-pgbouncer
spec:
  {{- if and .Values.pgbouncer.podDisruptionBudget.minAvailable (not (hasKey .Values.pgbouncer.podDisruptionBudget "maxUnavailable")) }}
  minAvailable: {{ .Values.pgbouncer.podDisruptionBudget.minAvailable }}
  {{- else if .Values.pgbouncer.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.pgbouncer.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "sentry.fullname" . }}-pgbouncer
{{- end }}
{{- end }}
