{{- if .Values.pgbouncer.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-pgbouncer
  labels:
    app: {{ template "sentry.fullname" . }}-pgbouncer
spec:
  replicas: {{ .Values.pgbouncer.replicas }}
  selector:
    matchLabels:
      app: {{ template "sentry.fullname" . }}-pgbouncer
  {{- if .Values.pgbouncer.updateStrategy }}
  strategy:
    {{ toYaml .Values.pgbouncer.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ template "sentry.fullname" . }}-pgbouncer
    spec:
      containers:
      - name: pgbouncer
        image: {{ .Values.pgbouncer.image.repository }}:{{ .Values.pgbouncer.image.tag }}
        imagePullPolicy: {{ .Values.pgbouncer.image.pullPolicy }}
        resources:
          {{ toYaml .Values.pgbouncer.resources | nindent 10 }}
        env:
          {{ include "sentry.pgbouncer.env" . | nindent 10 }}
          - name: PGBOUNCER_PORT
            value: "5432"
          - name: PGBOUNCER_AUTH_TYPE
            value: {{ .Values.pgbouncer.authType | quote }}
          - name: PGBOUNCER_MAX_CLIENT_CONN
            value: {{ .Values.pgbouncer.maxClientConn | quote }}
          - name: PGBOUNCER_DEFAULT_POOL_SIZE
            value: {{ .Values.pgbouncer.poolSize | quote }}
          - name: PGBOUNCER_POOL_MODE
            value: {{ .Values.pgbouncer.poolMode | quote }}
        ports:
          - containerPort: 5432
            name: pgbouncer
            protocol: TCP
      {{- if .Values.pgbouncer.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.pgbouncer.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.pgbouncer.tolerations }}
      tolerations:
        {{ toYaml .Values.pgbouncer.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.pgbouncer.affinity }}
      affinity:
        {{ toYaml .Values.pgbouncer.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.pgbouncer.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{ toYaml .Values.pgbouncer.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      {{- if .Values.pgbouncer.priorityClassName }}
      priorityClassName: "{{ .Values.pgbouncer.priorityClassName }}"
      {{- end }}
      terminationGracePeriodSeconds: 10
{{- end }}
